"""
app/bot/inline_buttons.py
─────────────────────────────────────────────────────────────────────────────
Telegram inline button callbacks for interactive tool responses.

Provides callback handlers for:
  - Buy/Sell confirmation buttons (after trade preview)
  - Close position buttons
  - Wallet linking confirmation
  - Creator tracking acknowledgment
  - Preference adjustment buttons

Buttons are generated by tool responses and handled via callback queries.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import ContextTypes

from app.bot.tools import execute_tool

log = logging.getLogger(__name__)

# Button callback data format: "action|param1=value1|param2=value2"
TRADE_CONFIRM_PREFIX = "trade_confirm"
TRADE_CANCEL_PREFIX = "trade_cancel"
CLOSE_POSITION_PREFIX = "close_position"
TRACK_CREATOR_PREFIX = "track_creator_confirm"
LINK_WALLET_PREFIX = "link_wallet_confirm"


def make_trade_preview_buttons(
    coin_symbol: str,
    action: str,
    amount_usd: float,
) -> InlineKeyboardMarkup:
    """
    Create inline buttons for trade preview response.

    Returns:
        InlineKeyboardMarkup with [Buy] [Cancel] buttons
    """
    confirm_data = f"{TRADE_CONFIRM_PREFIX}|coin={coin_symbol}|action={action}|amount={amount_usd}"
    cancel_data = f"{TRADE_CANCEL_PREFIX}|coin={coin_symbol}"

    keyboard = [
        [
            InlineKeyboardButton(f"✅ {action.upper()}", callback_data=confirm_data[:64]),
            InlineKeyboardButton("❌ Cancel", callback_data=cancel_data[:64]),
        ]
    ]

    return InlineKeyboardMarkup(keyboard)


def make_position_buttons(position_id: int) -> InlineKeyboardMarkup:
    """Create buttons for position management."""
    close_data = f"{CLOSE_POSITION_PREFIX}|pos_id={position_id}"

    keyboard = [
        [
            InlineKeyboardButton("Close Position", callback_data=close_data[:64]),
        ]
    ]

    return InlineKeyboardMarkup(keyboard)


def make_wallet_link_button(link_url: str) -> InlineKeyboardMarkup:
    """Create wallet link button (URL button)."""
    keyboard = [[InlineKeyboardButton("🔗 Link Wallet", url=link_url)]]
    return InlineKeyboardMarkup(keyboard)


# ── Callback Handlers ──────────────────────────────────────────────────────


async def handle_trade_confirm(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Handle trade confirmation button click."""
    query = update.callback_query
    user_id = query.from_user.id

    try:
        # Parse callback data
        # Format: "trade_confirm|coin=TEST|action=buy|amount=100"
        data = query.data
        params = {}
        for part in data.split("|")[1:]:
            if "=" in part:
                key, value = part.split("=", 1)
                params[key] = value

        coin_symbol = params.get("coin", "").upper()
        action = params.get("action", "buy").lower()
        amount_usd = float(params.get("amount", 0))

        if not all([coin_symbol, action, amount_usd]):
            await query.answer(
                "Invalid trade parameters. Try again.",
                show_alert=True,
            )
            return

        # Execute the trade via tool
        result = await execute_tool(
            telegram_user_id=user_id,
            tool_name="execute_trade",
            tool_args={
                "coin_symbol": coin_symbol,
                "action": action,
                "amount_usd": amount_usd,
            },
        )

        if result.get("success"):
            message = f"🎯 Trade executed!\n{result.get('data', {}).get('message', 'Trade confirmed')}"
            await query.answer("Trade executed!", show_alert=False)
        else:
            error_msg = result.get("error", "Trade failed")
            message = f"❌ Trade failed: {error_msg}"
            await query.answer(f"Trade failed: {error_msg}", show_alert=True)

        # Update message with result
        await query.edit_message_text(text=message)

    except Exception as exc:
        log.exception("trade_confirm_error", exc_info=True)
        await query.answer("An error occurred processing your trade.", show_alert=True)


async def handle_trade_cancel(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Handle trade cancellation button click."""
    query = update.callback_query

    try:
        await query.answer("Trade cancelled.", show_alert=False)
        await query.edit_message_text(
            text="❌ Trade cancelled.\n\nFeel free to ask about other trades or positions!"
        )
    except Exception as exc:
        log.exception("trade_cancel_error", exc_info=True)


async def handle_close_position(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Handle close position button click."""
    query = update.callback_query
    user_id = query.from_user.id

    try:
        # Parse callback data
        # Format: "close_position|pos_id=123"
        data = query.data
        params = {}
        for part in data.split("|")[1:]:
            if "=" in part:
                key, value = part.split("=", 1)
                params[key] = value

        position_id = int(params.get("pos_id", 0))

        if not position_id:
            await query.answer("Invalid position ID.", show_alert=True)
            return

        # TODO: Implement position closing in Phase 3
        message = "✅ Position close requested. (Future: Will be implemented in Phase 3)"
        await query.answer("Position close request submitted.", show_alert=False)
        await query.edit_message_text(text=message)

    except Exception as exc:
        log.exception("close_position_error", exc_info=True)
        await query.answer("An error occurred closing your position.", show_alert=True)


async def handle_wallet_link_confirm(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Handle wallet link confirmation button click."""
    query = update.callback_query

    try:
        # TODO: Integrate with wallet linking service in Phase 3
        message = "🔗 Wallet linking initiated. (Future: Will show link button)"
        await query.answer("Wallet linking started.", show_alert=False)
        await query.edit_message_text(text=message)

    except Exception as exc:
        log.exception("wallet_link_confirm_error", exc_info=True)


async def handle_track_creator_confirm(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Handle creator tracking confirmation button click."""
    query = update.callback_query

    try:
        await query.answer("Creator tracking confirmed.", show_alert=False)
        await query.edit_message_text(
            text="✅ Creator tracking confirmed! I'll monitor for signals."
        )

    except Exception as exc:
        log.exception("track_creator_confirm_error", exc_info=True)


# ── Button Handlers Registry ───────────────────────────────────────────────

BUTTON_HANDLERS = {
    TRADE_CONFIRM_PREFIX: handle_trade_confirm,
    TRADE_CANCEL_PREFIX: handle_trade_cancel,
    CLOSE_POSITION_PREFIX: handle_close_position,
    LINK_WALLET_PREFIX: handle_wallet_link_confirm,
    TRACK_CREATOR_PREFIX: handle_track_creator_confirm,
}


async def generic_callback_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """
    Generic callback query handler that routes to specific button handlers.

    This is called from callbacks.py after the query is already answered.
    Each handler can use query.answer() with show_alert=True if needed.
    """
    query = update.callback_query

    if not query:
        return

    callback_data = query.data
    log.info("callback_received", callback_data=callback_data)

    # Find matching handler by prefix
    for prefix, handler in BUTTON_HANDLERS.items():
        if callback_data.startswith(prefix):
            await handler(update, context)
            return

    # Unknown callback
    log.warning("unknown_callback", callback_data=callback_data)
